import os

print(" ")
print("----------Datos del estudiante----------")
print("|                                      |")
print("| Lenguajes formales y de programacion |")
print("|              Seccion: B-             |")
print("|           Carne: 201700965           |")
print("|                                      |")
print("----------------------------------------")
print(" ")
input("Presione enter para continuar")

# Recibir un enter, limpiar pantalla y mostrar el menu principal

os.system("cls")
print(" ")
print("------Menu Principal-------")
print("|                         |")
print("| 1. Menu Entretenimiento |")
print("| 2. Menu Educacion       |")
print("| 0. Salir                |")
print("|                         |")
print("---------------------------")
print(" ")
lectura = int(input('Presione el numero de la accion a realizar: '))

os.system("cls")
print(" ")
print("-------Menu Entretenimiento-------")
print("|                                |")
print("| 1. Carga del archivo .mascotas |")
print("| 0. Regresar al menu principal  |")
print("|                                |")
print("----------------------------------")
print(" ")
lectura = int(input('Presione el numero de la accion a realizar: '))

os.system("cls")
print(" ")
print("---------Menu Educacion----------")
print("|                               |")
print("| 1. Carga del archivo .edu     |")
print("| 2. Carga del archivo .almacen |")
print("| 0. Regresar al menu principal |")
print("|                               |")
print("---------------------------------")
print(" ")
lectura = int(input('Presione el numero de la accion a realizar: '))